// Generated by CoffeeScript 2.5.1
(function() {
  var YamlDb, fs, yaml;

  fs = require('fs-extra');

  yaml = require('js-yaml');

  YamlDb = class YamlDb {
    constructor(file1) {
      this.file = file1;
      if (fs.existsSync(this.file)) {
        this.dict = yaml.load(fs.readFileSync(this.file)) || {};
      } else {
        this.dict = {};
      }
    }

    get(key) {
      return this.dict[key];
    }

    set(key, val) {
      var exist, old, write;
      exist = key in this.dict;
      if (exist) {
        old = this.dict[key];
        if (old !== val) {
          write = true;
        }
      } else {
        write = true;
      }
      if (write) {
        this.dict[key] = val;
        fs.outputFileSync(this.file, yaml.dump(this.dict));
      }
      return false;
    }

  };

  module.exports = function(file) {
    return new YamlDb(file + ".yml");
  };

}).call(this);
